### ISSUE TITLE
运行中止

### ISSUE THREAD

**Issue by MiSanl** [Konano/weibo_archive#3]
不知道是不是获取过于频繁，是否需要增加一个时间范围的筛选接口呢，现在获取一会后就报错停止了：

```sh
..............
..............
[+] Downloading Photo 007ICWH5gy1hv1xhiasb9j30xm0mcaly from https://wx1.sinaimg.cn/large/0XXXXXXXXXXXXXxm0mcaly.jpg
[+] Downloading Comment 5094405446829791 0
[+] Downloading Comment 5094405446829791 138879531858089
[+] Downloading Comment 5094405446829791 138879531470370
[+] Downloading Comment 5094378840785197 0
[+] Downloading Comment 5094378840785197 138879530881299
[+] Downloading Comment 5094378840785197 138879529855464
[+] Downloading Comment 5094358725165177 0
[+] Downloading Comment 5094358725165177 138879529453715
[+] Downloading Comment 5094358725165177 138879528877804
[+] Downloading Comment 5094358725165177 82529558352426
[+] Downloading Comment 5093401672551255 0
[+] Downloading Comment 5093401672551255 138879512415334
[+] Downloading Comment 5093401672551255 138879470253527
[+] Downloading Comment 5093369871336236 0
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 353, in <module>
    posts = fetchPosts()
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 332, in fetchPosts
    fetchRelatedContent(card["mblog"])
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 268, in fetchRelatedContent
    fetchComments(post, "ext")
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 250, in fetchComments
    _comments, max_id = fetchFirstComments(mid, max_id, dirname)
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 221, in fetchFirstComments
    data = request(url, all_ret=True)
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 70, in request
    resp = __request(url, headers)
  File "E:\CommonFiles\LearnOrWork\CODElearn\Python\github\weibo_archive\run.py", line 62, in __request
    return requests.get(url, headers=headers, timeout=(30, 60)).json()
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>Shanhai Server</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
: 0

```

**Comment by Konano** [comment]
504 应该是服务器和网络的问题，出现的频率很高吗？
至于时间范围的筛选参数，看看还有没有人需要这个功能。
